@startuml
'https://plantuml.com/activity-diagram-beta
title Admin user deletes Firm

|Frontend|
start

:Admin User navigates to Firms Page;
:Admin selects Firm to Delete;
:System shows Confirmation Dialog;

if (Admin User Confirms) then (Yes)
    :Send DELETE Request;

    |Backend|

    :Receive Request;

    if (Is User Authorized?) then (Yes)
        if (Firm exists?) then (Yes)
            :Delete Firm;
            :Cancel all rentals that are associated to the deleted firm;

            if (Is Delete Successful?) then (Yes)
                :Create Success Response;
                (A)
                detach
            else (No)
                :Create Error Response;
                (A)
                detach
            endif
        else (No)
            :Create Error Response;
            (A)
            detach
        endif
    else (No)
        :Create Error Response;
        (A)
        detach
    endif

    (A)

    note right
        Send the response that was created in the previous step
    end note

    :Send Received Response;

    |Frontend|

    switch (ResponseType?)
    case (Success)
        :Show Success Message;
        stop
    case (Error)
        :Show Error Message;
        stop
    endswitch

else (No)
    |Frontend|
stop

endif

@enduml
