@startuml
'https://plantuml.com/activity-diagram-beta
title Delete Car

|Frontend|
start

:Firm User Navigates to Cars Page;
:Firm User Selects Car to Delete;
:Firm User Clicks Delete Button;
:Show Confirmation Dialog;

if (Firm User Confirms) then (Yes)
    :Send Delete Request;

    |Backend|

    :Receive Request;

    if (Is User Authorized?) then (Yes)
        if (Does Car Exist?) then (Yes)
            :Delete Car;

            if (Is Delete Successful?) then (Yes)
                :Create Success Response;
                (A)
                detach
            else (No)
                :Create Error Response;
                (A)
                detach
            endif
        else (No)
            :Create Error Response;
            (A)
            detach
        endif
    else (No)
        :Create Error Response;
        (A)
        detach
    endif

    (A)

    note right
        Send the response that was created in the previous step
    end note

    :Send Received Response;

    |Frontend|

    switch (ResponseType?)
    case (Success)
        :Show Success Message;
        stop
    case (Error)
        :Show Error Message;
        stop
    endswitch

else (No)
    |Frontend|
stop

endif

@enduml
