@startuml
'https://plantuml.com/activity-diagram-beta
title Cancel Rental

|Frontend|
start

:User navigates to Rentals Page;
:user selects Rental to Cancel;
:System shows Confirmation Dialog;

if (User Confirms) then (Yes)
    :Send PUT Request;

    |Backend|

    :Receive Request;

    if (Is User Authorized?) then (Yes)
        if (Rental exists?) then (Yes)
            :Delete Rental;

            if (Is Delete Successful?) then (Yes)
                :Create Success Response;
                (A)
                detach
            else (No)
                :Create Error Response;
                (A)
                detach
            endif
        else (No)
            :Create Error Response;
            (A)
            detach
        endif
    else (No)
        :Create Error Response;
        (A)
        detach
    endif

    (A)

    note right
        Send the response that was created in the previous step
    end note

    :Send Received Response;

    |Frontend|

    switch (ResponseType?)
    case (Success)
        :Show Success Message;
        stop
    case (Error)
        :Show Error Message;
        stop
    endswitch

else (No)
    |Frontend|
stop

endif

@enduml
